name: Execute notebook

on: [push]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python

      uses: actions/setup-python@v1

    - uses: yaananth/run-notebook@v1

      env:

        RUNNER: ${{ toJson(runner) }}

        SECRETS: ${{ toJson(secrets) }}

        GITHUB: ${{ toJson(github) }}

      with:

        notebook: "VPS_Linux_12GB_Ram.ipynb"

        params: "PATHTOPARAMS.json"

        isReport: False

        poll: True

    - uses: yaananth/run-notebook@v1

      env:

        RUNNER: ${{ toJson(runner) }}

        SECRETS: ${{ toJson(secrets) }}

        GITHUB: ${{ toJson(github) }}

      with:

        notebook: "VPS_Linux_12GB_Ram.ipynb"

    - uses: actions/upload-artifact@master

      if: always()

      with:

        name: output

        path: ${{ RUNNER.temp }}/nb-runner

      env:

        RUNNER: ${{ toJson(runner) }}
